# Generated by Django 6.0.6 on 2026-10-01 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CofidFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("food_group", models.CharField(blank=True, max_length=20)),
                ("energy_kcal", models.FloatField(blank=True, null=True)),
                ("energy_kj", models.FloatField(blank=True, null=True)),
                ("protein_g", models.FloatField(blank=True, null=True)),
                ("fat_g", models.FloatField(blank=True, null=True)),
                ("saturates_g", models.FloatField(blank=True, null=True)),
                ("carbohydrate_g", models.FloatField(blank=True, null=True)),
                ("sugars_g", models.FloatField(blank=True, null=True)),
                ("fibre_g", models.FloatField(blank=True, null=True)),
                ("salt_g", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CoFID food",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IngredientAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        help_text="Lowercase everyday name, e.g. 'chicken breast'.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aliases",
                        to="nutrition.cofidfood",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ingredient aliases",
                "ordering": ["alias"],
            },
        ),
    ]
