# Generated by Django 6.0.6 on 2026-10-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cofidfood",
            name="source",
            field=models.CharField(default="CoFID 2021", max_length=40),
        ),
    ]
