# Generated by Django 6.0.6 on 2026-10-02 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0002_cofidfood_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("kg_co2e_per_kg", models.FloatField()),
                ("land_use_change", models.FloatField(default=0)),
                ("farm", models.FloatField(default=0)),
                ("animal_feed", models.FloatField(default=0)),
                ("processing", models.FloatField(default=0)),
                ("transport", models.FloatField(default=0)),
                ("retail", models.FloatField(default=0)),
                ("packaging", models.FloatField(default=0)),
                ("losses", models.FloatField(default=0)),
            ],
            options={
                "verbose_name_plural": "carbon categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="cofidfood",
            name="carbon_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cofidfood",
            name="carbon_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="foods",
                to="nutrition.carboncategory",
            ),
        ),
    ]
