# Generated by Django 6.0.6 on 2026-10-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0003_carbon"),
    ]

    operations = [
        migrations.AddField(
            model_name="cofidfood",
            name="price_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cofidfood",
            name="price_per_kg_gbp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cofidfood",
            name="price_source",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
