# Generated by Django 6.0.6 on 2026-06-20 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='modification_instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='modification_type',
            field=models.CharField(blank=True, choices=[('healthier', 'Healthier'), ('cheaper', 'Cheaper'), ('quicker', 'Quicker'), ('vegetarian', 'Vegetarian'), ('spicier', 'Spicier'), ('simpler', 'Simpler'), ('custom', 'Custom')], max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='original_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_versions', to='recipes.recipe'),
        ),
    ]
