# Generated by Django 6.0.6 on 2026-06-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_modification_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='personal_notes',
            field=models.TextField(blank=True),
        ),
    ]
