# Generated by Django 6.0.6 on 2026-06-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_personal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='quality_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Final CulinaAI validation score out of 100.', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='validation_attempt_history',
            field=models.JSONField(blank=True, default=list, help_text='History of AI generation, correction and fallback attempts.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='validation_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of generation/correction attempts used.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='validation_badge',
            field=models.CharField(blank=True, help_text='Short validation badge shown in the UI.', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='validation_report',
            field=models.JSONField(blank=True, default=dict, help_text='Full CulinaAI validation report stored as JSON.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='validation_risk_level',
            field=models.CharField(blank=True, help_text='Risk level identified by the validation engine.', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='validation_status',
            field=models.CharField(blank=True, help_text='Final validation status such as Verified or Excellent / Verified.', max_length=100),
        ),
    ]
