# Generated by Django 6.0.6 on 2026-07-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_quality_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='community_views',
            field=models.PositiveIntegerField(default=0, help_text='Counts how many times this public recipe has been viewed.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Controls whether this recipe is visible in the community section.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='public_shared_at',
            field=models.DateTimeField(blank=True, help_text='Stores when the recipe was shared with the community.', null=True),
        ),
    ]
