# Generated by Django 6.0.6 on 2026-07-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_community_views_recipe_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='generated_image',
            field=models.ImageField(blank=True, help_text='AI-generated image for this recipe.', null=True, upload_to='recipe_images/'),
        ),
    ]
