# Generated by Django 6.0.6 on 2026-07-08 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_generated_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('recipe_text', models.TextField()),
                ('recipe_prompt', models.TextField(blank=True)),
                ('ingredients_text', models.TextField(blank=True)),
                ('cuisine_name', models.CharField(blank=True, max_length=120)),
                ('meal_type_name', models.CharField(blank=True, max_length=120)),
                ('dietary_preferences', models.JSONField(blank=True, default=list, help_text='Diet preferences selected when the recipe was generated.')),
                ('allergies', models.TextField(blank=True)),
                ('cooking_time_minutes', models.PositiveIntegerField(default=30)),
                ('servings', models.PositiveIntegerField(blank=True, help_text='Number of people/servings requested by the user.', null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('spice_level', models.CharField(blank=True, max_length=100)),
                ('budget_level', models.CharField(blank=True, max_length=100)),
                ('nutrition_goal', models.CharField(blank=True, max_length=100)),
                ('cooking_equipment', models.JSONField(blank=True, default=list)),
                ('utensils', models.JSONField(blank=True, default=list)),
                ('additional_notes', models.TextField(blank=True)),
                ('generated_image', models.ImageField(blank=True, help_text='AI-generated image connected to this history item.', null=True, upload_to='recipe_history_images/')),
                ('generated_image_prompt', models.TextField(blank=True)),
                ('quality_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('validation_status', models.CharField(blank=True, max_length=100)),
                ('validation_risk_level', models.CharField(blank=True, max_length=50)),
                ('validation_badge', models.CharField(blank=True, max_length=50)),
                ('validation_attempts', models.PositiveSmallIntegerField(default=0)),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('validation_attempt_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_recipe', models.ForeignKey(blank=True, help_text='Links this history item to a saved recipe if the user saves it later.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recipe History',
                'verbose_name_plural': 'Recipe History',
                'ordering': ['-created_at'],
            },
        ),
    ]
