# Generated by Django 6.0.6 on 2026-07-09 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(help_text='Name of the pantry ingredient.', max_length=120)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Quantity available, for example 1.5 or 500.', max_digits=8, null=True)),
                ('unit', models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'millilitres'), ('l', 'litres'), ('pcs', 'pieces'), ('tbsp', 'tablespoons'), ('tsp', 'teaspoons'), ('pack', 'pack'), ('other', 'other')], default='pcs', max_length=20)),
                ('category', models.CharField(choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('dairy', 'Dairy'), ('grain', 'Grain / Rice / Pasta'), ('protein', 'Protein'), ('spice', 'Spice / Seasoning'), ('sauce', 'Sauce / Condiment'), ('frozen', 'Frozen'), ('other', 'Other')], default='other', max_length=30)),
                ('expiry_date', models.DateField(blank=True, help_text='Optional expiry date for this ingredient.', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Marks whether the item is still available in the pantry.')),
                ('notes', models.TextField(blank=True, help_text='Optional notes, for example brand, storage location or freshness.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiry_date', 'ingredient_name'],
                'indexes': [models.Index(fields=['user', 'ingredient_name'], name='recipes_pan_user_id_047c42_idx'), models.Index(fields=['user', 'expiry_date'], name='recipes_pan_user_id_05dfd9_idx')],
            },
        ),
    ]
