# Generated by Django 6.0.6 on 2026-07-09 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_pantryitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='AI Cooking Assistant', max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_chat_sessions', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CookingChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('quick_prompt_label', models.CharField(blank=True, max_length=120)),
                ('ai_model', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='recipes.cookingchatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cookingchatsession',
            index=models.Index(fields=['user', 'recipe'], name='recipes_coo_user_id_873db7_idx'),
        ),
        migrations.AddIndex(
            model_name='cookingchatsession',
            index=models.Index(fields=['updated_at'], name='recipes_coo_updated_c7350e_idx'),
        ),
        migrations.AddIndex(
            model_name='cookingchatmessage',
            index=models.Index(fields=['session', 'created_at'], name='recipes_coo_session_0d95ba_idx'),
        ),
        migrations.AddIndex(
            model_name='cookingchatmessage',
            index=models.Index(fields=['sender'], name='recipes_coo_sender_0f9259_idx'),
        ),
    ]
