# Generated by Django 6.0.6 on 2026-07-25 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_cookingchatsession_cookingchatmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Refrigerator image uploaded by the user.', upload_to='fridge_scans/')),
                ('detected_items', models.JSONField(blank=True, default=list, help_text='Raw list of ingredients detected by the AI scanner.')),
                ('confirmed_items', models.JSONField(blank=True, default=list, help_text='Final ingredient list confirmed or edited by the user.')),
                ('raw_ai_response', models.TextField(blank=True, help_text='Raw AI response from the refrigerator image scan.')),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the refrigerator scan.', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Stores scanning or AI error details if the scan fails.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fridge Scan',
                'verbose_name_plural': 'Fridge Scans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'scan_status'], name='recipes_fri_user_id_c003a7_idx'), models.Index(fields=['created_at'], name='recipes_fri_created_4e4ce2_idx')],
            },
        ),
    ]
