# Generated by Django 6.0.6 on 2026-10-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_fridgescan"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="insights",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="recipehistory",
            name="insights",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
