# Generated by Django 6.0.6 on 2026-10-08 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_recipe_insights"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CookingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_title", models.CharField(max_length=200)),
                ("cuisine_name", models.CharField(blank=True, max_length=120)),
                ("steps_total", models.PositiveSmallIntegerField(default=0)),
                ("steps_completed", models.PositiveSmallIntegerField(default=0)),
                ("active_seconds", models.PositiveIntegerField(default=0)),
                ("finished", models.BooleanField(default=False)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("great", "Turned out great"),
                            ("ok", "It was OK"),
                            ("bad", "Didn't go well"),
                        ],
                        max_length=10,
                    ),
                ),
                ("voice_used", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cooking_sessions",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooking_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CookingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("learn_from_cooking", models.BooleanField(default=True)),
                ("english", models.CharField(blank=True, max_length=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooking_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CookingStepRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("text", models.TextField(blank=True)),
                ("planned_minutes", models.PositiveSmallIntegerField(default=0)),
                ("timer_from_text", models.BooleanField(default=False)),
                ("seconds_open", models.PositiveIntegerField(default=0)),
                ("timer_used", models.BooleanField(default=False)),
                ("repeats", models.PositiveSmallIntegerField(default=0)),
                (
                    "trouble",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("longer", "Took longer"),
                            ("unclear", "Instructions unclear"),
                            ("technique", "Tricky technique"),
                        ],
                        max_length=10,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="recipes.cookingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "number"],
            },
        ),
        migrations.AddIndex(
            model_name="cookingsession",
            index=models.Index(
                fields=["user", "started_at"], name="recipes_coo_user_id_239539_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cookingsteprecord",
            constraint=models.UniqueConstraint(
                fields=("session", "number"), name="unique_step_per_cooking_session"
            ),
        ),
    ]
