# Generated by Django 6.0.6 on 2026-10-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_cooking_learning"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookingsteprecord",
            name="note",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="cookingsteprecord",
            name="went_fine",
            field=models.BooleanField(default=False),
        ),
    ]
