# Generated by Django 6.0.6 on 2026-10-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0013_step_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookingsession",
            name="timers_adjusted",
            field=models.BooleanField(default=False),
        ),
    ]
